### ISSUE TITLE
Obj_AI_Base.OnBasicAttack not consistently working on 7.5

### ISSUE THREAD

**Issue by pib314** [EloBuddy/EloBuddy.Issues#129] opened 2017-03-20 20:02 UTC
Previously, this event would be triggered on any basic attack, but since patch 7.5, I'm not seeing this for champions. The method does not get called when a champion auto-attacks a target.

**Comment by TonyRL** [comment] 2017-03-24 18:47
The issue is fixed with [Core#611](https://github.com/EloBuddy/EloBuddy.Dependencies/commit/5d8c3cdaa5f0786fffe2abc0639b24f5c8afb60d)

**Closed as completed by TonyRL** 2017-03-24 18:47 UTC

**Comment by pib314** [comment] 2017-03-26 07:11
Is this deployed? I have the latest core, and it doesn't appear to work properly. I'm spectating a game, and still barely seeing any basic attacks being triggered.

**Comment by TonyRL** [comment] 2017-03-26 11:07
I tried in practice tool and it works good.

**Comment by pib314** [comment] 2017-03-26 21:24
Ah, I see it now. I didn't have the latest version. Thanks!
