### ISSUE TITLE
EB not installing add-ons

### ISSUE THREAD

**Issue by alecsucks3** [EloBuddy/EloBuddy.Issues#39] opened 2016-02-04 12:35 UTC
Hi!, ive tried deleteing everything, restarting computer, reinstalling and i cant seem to get EB to install scripts! i know a large amount of people from the community having the same problem if you check the support section on the main forum. any possible fixes?

**Comment by ghost** [comment] 2016-02-05 21:59
Duplicate of #40 (40 has better details)

**Closed as completed** 2016-02-22 20:06 UTC
