### ISSUE TITLE
Addons still giving error upon installing attempt. 

### ISSUE THREAD

**Issue by Sitibi** [EloBuddy/EloBuddy.Issues#28] opened 2016-01-30 21:37 UTC
Hi, I'm new. When installing any add-on manually via a link githab or by clicking "install" I have an error. Read forum, nothing helps. What's wrong?
 Logs
 [31.01.2016 0:04:43] 
 Installing addon: "https://github.com/s...ddons EvadePlus".
 [31.01.2016 0:04:43] 
 Updating addon: "EvadePlus" with url: "https://github.com/s.../elobuddyaddons" and project name: "EvadePlus.csproj"
 [31.01.2016 0:04:43] 
 Cloning repository: "https://github.com/s.../elobuddyaddons" to directory: "C:\Users\User\AppData\Roaming\EloBuddy\Repositories\4A172269".
 [31.01.2016 0:04:47] 
 Successfully cloned repository: "https://github.com/s.../elobuddyaddons" to directory: "C:\Users\User\AppData\Roaming\EloBuddy\Repositories\4A172269".
 [31.01.2016 0:04:47] 
 Compiling project: "C:\Users\User\AppData\Roaming\EloBuddy\Repositories\4A172269\EvadePlus.csproj".
 [31.01.2016 0:04:49] 
 Failed to compile project: "C:\Users\User\AppData\Roaming\EloBuddy\Repositories\4A172269\EvadePlus\EvadePlus.csproj". Build log file saved to "D:\elo\Logs\compile_log_EvadePlus_F4387D46.txt".
 [31.01.2016 0:04:49] 
 Finished updating addon: "EvadePlus", result: CompilingError (url: "https://github.com/s.../elobuddyaddons", project: "EvadePlus.csproj", directory "C:\Users\User\AppData\Roaming\EloBuddy\Repositories\4A172269")
 [31.01.2016 0:04:49] 
 Failed to install addon: "https://github.com/s...ddons EvadePlus". Addon state: "CompilingError". The addon either did not update or did not compile!

**Comment by Hellsing** [comment] 2016-01-30 21:39
As it's a compile error for EvadePlus I've assigned @stefsot with this issue, thanks for reporting, even though it's not really a bug as it's working for everyone else just fine.

**Comment by Sitibi** [comment] 2016-01-30 21:43
I have this error on all addons, just logs brought only this addon.

**Comment by Sitibi** [comment] 2016-01-30 21:46
I think the case in the framework 4.5, which I can not install on windows 10.

**Comment by Sitibi** [comment] 2016-01-30 21:47
[31.01.2016 0:23:22] <Info>
 Finished updating addon: "EloBuddyAddons", result: CompilingError (url: "", project: "EloBuddyAddons.git", directory "")
[31.01.2016 0:23:22] <Error>
 Failed to install addon: "https://github.com/stefsot/EloBuddyAddons.git". Addon state: "CompilingError". The addon either did not update or did not compile!
[31.01.2016 0:25:18] <Info>
 Installing addon: "D:\eloads\EloBuddyAddons-master\EvadePlus\EvadePlus.csproj".
[31.01.2016 0:25:18] <Info>
 Compiling project: "D:\eloads\EloBuddyAddons-master\EvadePlus\EvadePlus.csproj".
[31.01.2016 0:25:18] <Error>
 Failed to compile project: "D:\eloads\EloBuddyAddons-master\EvadePlus\EvadePlus.csproj". Build log file saved to "D:\elo\Logs\compile_log_EvadePlus_E25B39A4.txt".
[31.01.2016 0:25:18] <Info>
 Finished updating addon: "EvadePlus", result: CompilingError (url: "", project: "EvadePlus.csproj", directory "")
[31.01.2016 0:25:18] <Error>
 Failed to install addon: "D:\eloads\EloBuddyAddons-master\EvadePlus\EvadePlus.csproj". Addon state: "CompilingError". The addon either did not update or did not compile!
[31.01.2016 0:25:31] <Info>
 Installing addon: "D:\eloads\EloBuddyAddons-master\NotBrand\NotBrand.csproj".
[31.01.2016 0:25:31] <Info>
 Compiling project: "D:\eloads\EloBuddyAddons-master\NotBrand\NotBrand.csproj".
[31.01.2016 0:25:31] <Error>
 Failed to compile project: "D:\eloads\EloBuddyAddons-master\NotBrand\NotBrand.csproj". Build log file saved to "D:\elo\Logs\compile_log_NotBrand_1982455B.txt".
[31.01.2016 0:25:31] <Info>
 Finished updating addon: "NotBrand", result: CompilingError (url: "", project: "NotBrand.csproj", directory "")
[31.01.2016 0:25:31] <Error>
 Failed to install addon: "D:\eloads\EloBuddyAddons-master\NotBrand\NotBrand.csproj". Addon state: "CompilingError". The addon either did not update or did not compile!
[31.01.2016 0:26:03] <Info>
 Installing addon: "D:\eloads\EloBuddyAddons-master\NotBrand\NotBrand.csproj".
[31.01.2016 0:26:03] <Info>
 Compiling project: "D:\eloads\EloBuddyAddons-master\NotBrand\NotBrand.csproj".
[31.01.2016 0:26:03] <Error>
 Exception during compilation.
Project: "D:\eloads\EloBuddyAddons-master\NotBrand\NotBrand.csproj"
Exception: System.IO.DirectoryNotFoundException: Не удалось найти часть пути "C:\Users\User\AppData\Roaming\EloBuddy\Addons\Libraries".
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.FileSystemEnumerableIterator`1.CommonInit()
   в System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   в System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   в EloBuddy.Loader.Compilers.ProjectCompiler.‫⁬⁬‫​‮⁮⁭⁪‏⁭‬‪‪⁬‪‪‏‫⁬‭‍⁪‬⁯‭‌⁭⁮⁪‏‎‎⁭⁯⁫⁮‮‬⁫‮(String , String , SearchOption )
   в EloBuddy.Loader.Compilers.ProjectCompiler.Compile(Project project, String logFile)
   в EloBuddy.Loader.Compilers.ProjectCompiler.Compile(String projectFile, String logFile)
   в EloBuddy.Loader.Data.ElobuddyAddon.Compile(Boolean refreshDisplay)
[31.01.2016 0:26:03] <Info>
 Finished updating addon: "NotBrand", result: CompilingError (url: "", project: "NotBrand.csproj", directory "")
[31.01.2016 0:26:03] <Error>
 Failed to install addon: "D:\eloads\EloBuddyAddons-master\NotBrand\NotBrand.csproj". Addon state: "CompilingError". The addon either did not update or did not compile!

**Comment by stefsot** [comment] 2016-01-30 21:49
reinstall elobuddy

**Comment by Sitibi** [comment] 2016-01-30 21:50
Didn't help

**Comment by Sitibi** [comment] 2016-01-30 21:50
I tried to do everything that is written on the forum.

**Comment by Sitibi** [comment] 2016-01-30 21:52
Also, I noticed that many people have this  problem, but there is no answer.

**Comment by Sitibi** [comment] 2016-01-30 22:08
And I would like apologize for my english.

**Comment by Sitibi** [comment] 2016-01-31 05:35
![ellob bug](https://cloud.githubusercontent.com/assets/15304087/12700479/8f7a4b06-c7f5-11e5-9304-f66a572cf085.png)

**Comment by Sitibi** [comment] 2016-01-31 05:36
No one can help me?

**Comment by Sitibi** [comment] 2016-01-31 07:47
I deleted all the framework and installed 4.5, did not help. I do not know what else to do!

**Comment by Hellsing** [comment] 2016-01-31 10:25
Since nothing has helped so far I think you should give it a try to install the following package which includes all known runtimes:

http://www.computerbase.de/downloads/systemtools/all-in-one-runtimes/

Please install it completely and reboot your computer afterwards. Once that is done, go to your %AppData% folder and find the folder named "EloBuddy" and delete it. And once that's done reinstall EloBuddy aswell to the default installation path (C:/Programs (x86)/EloBuddy).

When you have completed the above tasks please run EloBuddy again and see if the issue is resolved, if not, then I don't have an idea what might be wrong with your computer as EloBuddy is confirmed working for everyone else, this is why I'm closing this issue now with this message aswell.

Good luck fixing your issue.

**Closed as completed by Hellsing** 2016-01-31 10:25 UTC
Labels: help wanted
